pipeline {
    agent any
    tools { 
        go '1.19'
        nodejs 'NodeJS 24' // Name as defined in Jenkins configuration
    }

    stages {
        stage('Unit Tests - Backend') {
            steps {
                dir('bugtracker-backend') {
 sh 'go install github.com/jstemmer/go-junit-report/v2@latest' // Install the tool
sh 'export PATH=$PATH:/c/Users/simon/go/bin' // Add GOPATH bin to PATH
            sh 'go version'
            sh 'go test -v ./... 2>&1 | go-junit-report > test-results.xml'
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/test-results.xml'
                }
            }
        }
        stage('Build and Test Frontend') {
            steps {
                dir('bugtracker-frontend') {
                    sh 'npm --version'
                    sh 'npm install'
                    sh 'npm test' // or another frontend build/test command
                }
            }
            post {
                always {
                 junit 'bugtracker-frontend/test-results.xml'   
                }
            }

        }
    }
}
